title: "The Intuitive Machine"
description: "Thoughts and Stories"
author: "LuaGeeko"
theme: minima
markdown: kramdown
highlighter: rouge
show_excerpts: true
paginate: 5

# URLs
url: "https://luaGeeko.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag